---
title: "Lab 09: Annotating Data Visualizations"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(warning = FALSE)
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(fig.height = 5)
knitr::opts_chunk$set(fig.width = 8.5)
knitr::opts_chunk$set(out.width = "100%")
knitr::opts_chunk$set(dpi = 300)

library(readr)
library(ggplot2)
library(dplyr)
library(viridis)
theme_set(theme_minimal())
```



```{r}
trump <- read_csv("https://statsmaths.github.io/stat_data/trump_approval.csv")
```


```{r}
murder <- read_csv("https://statsmaths.github.io/stat_data/murder_by_city.csv")
```



```{r}
djia <- read_csv("https://statsmaths.github.io/stat_data/djia_daily.csv")
```


## Analysis
### Lidia Amanuel
#### This visualization plots approval and disapproval rates during the Trump presidency. We can see that the ratings of the two variables are slowly progressing towards each other.
```{r}
ggplot(trump, aes(date, approve)) +
  geom_point(color="salmon") +
  geom_point(aes(y= disapprove), color= "olivedrab") +
  xlab("Dates") +
  ylab("Ratings") +
  annotate("text", x = as.Date("2018-02-12"), y = 43.30393, label = "Most Recent Approval", color = "blue") +
  annotate("text", x = as.Date("2018-02-12"), y = 52.30949, label = "Most Recent Disapproval ", color = "purple") +
  annotate("point", x= as.Date("2019-02-12"), y= 32.3025, color= "pink") +
  annotate("text", x= as.Date("2019-02-12"), y= 32.3025, label = "Projected", color = "orange")

```
```









